### ISSUE TITLE
R2 and R5 capacitor

### ISSUE THREAD

**Issue by tr4usut** [taHC81/pzem017-wireless#1]
How many ohm capacitor you replace for r2 and r5. Tks.

**Comment by taHC81** [comment]
Hi, they've been burnt, so replaced with a same 10R (10 ohm). And these are resistors, not capacitors :)

**Comment by taHC81** [comment]
Hi, they've been burnt, so replaced with a same 10R (10 ohm). And these are resistors, not capacitors :)
